// npm run calibrate                    calibrate the playable roster under the D8 feel
// npm run calibrate -- --feel current  …under today's feel instead
// npm run calibrate -- --rounds 6 --seeds 3
//
// The calibration lab (02-PLAN P13.4). Writes PROPOSALS — never the real
// roster — to src/data/calibration/<feel>/: one raw character JSON per
// fighter (the A/B variant), report.json (every change with its reason,
// before/after matrices) and report.md. Approval + apply is P13.6.
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ROSTER } from '../../src/data/roster';
import { calibrate } from '../../src/bench/lab/calibrate';
import { loadRaw } from '../../src/bench/lab/raw';
import { matrixMarkdown } from '../../src/bench/lab/matrix';
import type { FeelProfile } from '../../src/bench/lab/feel';

const args = process.argv.slice(2);
const opt = (n: string): string | undefined => {
  const i = args.indexOf(`--${n}`);
  return i >= 0 ? args[i + 1] : undefined;
};
const feel = (opt('feel') ?? 'd8') as FeelProfile;
const ids = ROSTER.filter((r) => r.playable).map((r) => r.id);
const t0 = Date.now();
const res = calibrate(loadRaw(ids), ids, {
  feel,
  seeds: Number(opt('seeds') ?? 2),
  rounds: Number(opt('rounds') ?? 5),
  onLog: (l) => console.log(l),
});
const dir = join('src/data/calibration', feel);
mkdirSync(dir, { recursive: true });
for (const id of ids) writeFileSync(join(dir, `${id}.json`), JSON.stringify(res.raw[id], null, 2) + '\n');

const summary = (m: typeof res.before): Record<string, { winRate: number; worst: unknown; best: unknown }> =>
  Object.fromEntries(ids.map((id) => [id, { winRate: Math.round(m.fighters[id].winRate * 1000) / 1000, worst: m.fighters[id].worst, best: m.fighters[id].best }]));
writeFileSync(join(dir, 'report.json'), JSON.stringify({
  feel,
  generated: new Date().toISOString(),
  changes: res.changes,
  rejected: res.rejected,
  before: { fighters: summary(res.before), cells: res.before.cells },
  after: { fighters: summary(res.after), cells: res.after.cells },
}, null, 2) + '\n');

const byChar = (id: string) => res.changes.filter((c) => c.char === id);
const pct = (x: number): string => `${Math.round(x * 100)}%`;
const md = [
  `# Calibration proposal — feel: ${feel}`,
  '',
  `Generated by \`npm run calibrate -- --feel ${feel}\` in ${Math.round((Date.now() - t0) / 1000)} s. **Proposals only** — nothing here is live until approved (02-PLAN P13.6).`,
  '',
  '| Fighter | Win % before → after | Changes (feel / art / bands / balance) |',
  '|---|--:|---|',
  ...ids.map((id) => {
    const c = byChar(id);
    const n = (s: string): number => c.filter((x) => x.stage === s).length;
    return `| ${id} | ${pct(res.before.fighters[id].winRate)} → ${pct(res.after.fighters[id].winRate)} | ${n('feel')} / ${n('art')} / ${n('bands')} / ${n('balance')} |`;
  }),
  '',
  ...(res.rejected.length ? ['## Reverted', '', ...res.rejected.map((r) => `- ${r}`), ''] : []),
  '## Per fighter',
  '',
  ...ids.flatMap((id) => {
    const c = byChar(id);
    const fb = res.before.fighters[id];
    const fa = res.after.fighters[id];
    const mv = (x: (typeof c)[number]): string => `${x.move ?? id}${x.strength ? ` ${x.strength.toUpperCase()}` : ''}`;
    const v = (x: unknown): string => (typeof x === 'object' ? JSON.stringify(x) : String(x));
    const art = c.filter((x) => x.stage === 'art');
    const bands = c.filter((x) => x.stage === 'bands');
    const feelC = c.filter((x) => x.stage === 'feel');
    const bal = c.filter((x) => x.stage === 'balance');
    // balance: summarize as the net damage multiplier, reach multiplier, health
    const dmg = bal.filter((x) => x.field === 'damage');
    const firstLast = (field: string): string => {
      const xs = bal.filter((x) => x.field === field);
      return xs.length ? `${v(xs[0].from)} → ${v(xs[xs.length - 1].to)}` : '';
    };
    const dmgRatio = (() => {
      const byKey = new Map<string, { from: number; to: number }>();
      for (const x of dmg) {
        const k = mv(x);
        const e = byKey.get(k);
        if (e) e.to = x.to as number;
        else byKey.set(k, { from: x.from as number, to: x.to as number });
      }
      const rs = [...byKey.values()].map((e) => e.to / e.from);
      return rs.length ? (rs.reduce((p, q) => p + q, 0) / rs.length).toFixed(2) : null;
    })();
    const reachRatio = (() => {
      const xs = bal.filter((x) => x.field === 'hitbox');
      const why = xs.length ? xs[xs.length - 1].why : '';
      return xs.length ? `${new Set(xs.map((x) => x.move)).size} moves (last step: ${why.split('→')[1]?.trim() ?? ''})` : null;
    })();
    const hp = firstLast('health');
    return [
      `### ${id} — ${pct(fb.winRate)} → ${pct(fa.winRate)}`,
      '',
      `Worst matchup ${fb.worst ? `${fb.worst.vs} ${pct(fb.worst.winRate)}` : '—'} → ${fa.worst ? `${fa.worst.vs} ${pct(fa.worst.winRate)}` : '—'} · best ${fb.best ? `${fb.best.vs} ${pct(fb.best.winRate)}` : '—'} → ${fa.best ? `${fa.best.vs} ${pct(fa.best.winRate)}` : '—'}`,
      '',
      `- **Feel (${feel}):** ${feelC.length} edits${feelC.find((x) => x.field === 'walkSpeed') ? ` · walk ${v(feelC.find((x) => x.field === 'walkSpeed')!.from)} → ${v(feelC.find((x) => x.field === 'walkSpeed')!.to)} px/tick` : ''}`,
      ...(art.length ? [`- **Hitboxes from the art (${art.length}):** ${art.map((x) => `${mv(x)} (${x.why})`).join('; ')}`] : ['- **Hitboxes from the art:** none needed']),
      ...(bands.length ? [`- **MKS-1 bands (${bands.length}):**`, ...bands.map((x) => `  - ${mv(x)} \`${x.field}\` ${v(x.from)} → ${v(x.to)} — ${x.why}`)] : ['- **MKS-1 bands:** already in band']),
      `- **Balance:** ${dmgRatio ? `damage ×${dmgRatio} (avg over moves)` : 'damage unchanged'}${hp ? ` · health ${hp}` : ''}${reachRatio ? ` · reach on ${reachRatio}` : ''}`,
      '',
    ];
  }),
  matrixMarkdown(res.after, 'After — matchup matrix'),
].join('\n');
writeFileSync(join(dir, 'report.md'), md);
console.log(md.split('## Grid')[0]);
console.log(`→ ${dir}/report.md`);
