// Stage registry. Stages are data: generated by tools/gen-stage.mjs from
// assets/stage-inspo/<FOLDER>/, packed to public/assets/backgrounds/stages/.
// A character claims a home stage with an optional `stage: "<id>"` field in
// its JSON — used by the stage-select dialog to badge home stages.
import type { Defs } from '../engine';

export interface StageEntry {
  id: string;
  name: string;
  /** path under public/, relative to the page (matches BootScene loads) */
  file: string;
  /** Optional parallax layers, ordered back-to-front by the renderer. */
  layers?: {
    sky?: { file: string; factor?: number };
    far?: { file: string; factor?: number };
    near?: { file: string; factor?: number };
    floor?: { file: string; factor?: number };
  };
}

const stage = (id: string, name: string): StageEntry => ({
  id,
  name,
  file: `assets/backgrounds/stages/${id}.jpg`,
});

export const STAGES: StageEntry[] = [
  // the original MVP stage keeps its legacy file location
  { id: 'salton', name: 'SALTON SHORELINE', file: 'assets/backgrounds/salton-shoreline.jpg' },
  stage('altar', 'ALTAR'),
  stage('bbac', 'BBAC'),
  stage('chiba', 'CHIBA'),
  {
    ...stage('chiba-roof', 'CHIBA ROOF'),
    layers: {
      sky: { file: 'assets/backgrounds/stages/chiba-roof/sky.png', factor: 0.14 },
      far: { file: 'assets/backgrounds/stages/chiba-roof/far.png', factor: 0.34 },
      near: { file: 'assets/backgrounds/stages/chiba-roof/near.png', factor: 0.68 },
      floor: { file: 'assets/backgrounds/stages/chiba-roof/floor.png', factor: 1.0 },
    },
  },
  stage('dodecahedron', 'DODECAHEDRON'),
  stage('dome', 'DOME'),
  stage('drive-in', 'DRIVE IN'),
  stage('estates', 'ESTATES'),
  stage('institute', 'INSTITUTE'),
  stage('mars', 'MARS'),
  stage('mimos', 'MIMOS'),
  stage('neptune', 'NEPTUNE'),
  stage('painted-canyon', 'PAINTED CANYON'),
  stage('saturn', 'SATURN'),
  stage('ski-inn', 'SKI INN'),
  stage('shipwreck', 'SHIPWRECK'),
  stage('the-range', 'THE RANGE'),
  stage('van', 'VAN'),
];

export function stageById(id: string): StageEntry | undefined {
  return STAGES.find((s) => s.id === id);
}

/** Which of these characters (if any) calls this stage home. */
export function stageOwner(stageId: string, charIds: string[], defs: Defs): string | null {
  for (const c of charIds) if (defs[c]?.stage === stageId) return c;
  return null;
}
